{% set name = "pydarm" %}
{% set version = "0.0.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pydarm-{{ version }}.tar.gz
  sha256: f647f7f116533cd07d65eef66b2b0217302ae5f9835ee41e882e400b60fa57ed

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.7
    - setuptools-scm
  run:
    - corner
    - dttxml
    - emcee
    - gwpy
    - h5py
    - matplotlib-base
    - numpy
    - python >=3.7
    - requests
    - scikit-learn <=1.0.2
    - scipy

test:
  imports:
    - pydarm
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://pypi.org/project/pydarm/
  summary: pyDARM modeling package for LIGO detector calibration
  license: GPL-3.0-or-later
  license_file: LICENSE

extra:
  recipe-maintainers:
    - eagoetz
