{% set name = "pydarm" %}
{% set version = "1.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/pydarm-{{ version }}.tar.gz
  sha256: bb2e779a715503c9bd40942480c5aabee812c2b7aa21b12f0e33af34e3e9af40

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools-scm
  run:
    - corner
    - dttxml
    - emcee
    - gitpython
    - gpflow
    - gpstime
    - gwpy
    - h5py
    - ligo-scald
    - matplotlib-base
    - numpy <1.25
    - pyepics
    - python >={{ python_min }}
    - requests
    - scikit-learn >=1.1.0
    - scipy
    - tensorflow ==2.15.0
    - tensorflow-probability ==0.23.0

test:
  imports:
    - pydarm
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://pypi.org/project/pydarm/
  doc_url: https://calibration.docs.ligo.org/pydarm
  summary: pyDARM modeling package for LIGO detector calibration
  license: GPL-3.0-or-later
  license_file: LICENSE

extra:
  recipe-maintainers:
    - eagoetz
