{% set name = "pydarm" %}
{% set version = "1.0.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/pydarm-{{ version }}.tar.gz
  sha256: fb649b950a79f035c3c4648a07d26e1e8edca0b2601240f15c44327d4da84b4d

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools-scm
  run:
    - corner
    - dttxml
    - emcee
    - gitpython
    - gpflow
    - gpstime
    - gwpy
    - h5py
    - ligo-scald
    - matplotlib-base
    - numpy <1.25
    - pyepics
    - python >={{ python_min }}
    - requests
    - scikit-learn >=1.1.0
    - scipy
    - tensorflow ==2.15.0
    - tensorflow-probability ==0.23.0

test:
  imports:
    - pydarm
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://pypi.org/project/pydarm/
  doc_url: https://calibration.docs.ligo.org/pydarm
  summary: pyDARM modeling package for LIGO detector calibration
  license: GPL-3.0-or-later
  license_file: LICENSE

extra:
  recipe-maintainers:
    - eagoetz
