{% set name = "pydarm" %}
{% set version = "0.0.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pydarm-{{ version }}.tar.gz
  sha256: 3501aa74c879549530f9e3b5064701200c0c80c97d0111d8c930cd57bcf88940

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.8
    - setuptools-scm
  run:
    - corner
    - dttxml
    - emcee
    - gwpy
    - h5py
    - matplotlib-base
    - numpy
    - python >=3.8
    - requests
    - scikit-learn >=1.1.0
    - scipy
    - ezca

test:
  imports:
    - pydarm
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://pypi.org/project/pydarm/
  summary: pyDARM modeling package for LIGO detector calibration
  license: GPL-3.0-or-later
  license_file: LICENSE

extra:
  recipe-maintainers:
    - eagoetz
